name: Schedule Merge Staging into Main

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Excecute manually'
        required: true
        default: 'yes'
  schedule:
    - cron: '0 17 */30 * *'  # execute ever 30 days at 17:00 UTC

permissions: write-all

jobs:
  install:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '^18.0.0'
          cache: 'npm'

      - name: Install
        run: npm ci

      - uses: actions/cache@v3.3.2
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
  lint:
    runs-on: ubuntu-latest
    needs: install
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '^18.0.0'
          cache: 'npm'

      - uses: actions/cache@v3.3.2
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}

      - run: npm run lint

  build:
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - uses: actions/checkout@v4.1.1

      - name: Setup node
        uses: actions/setup-node@v4.0.0
        with:
          node-version: '^18.0.0'
          cache: 'npm'

      - uses: actions/cache@v3.3.2
        with:
          path: ./*
          key: ${{ github.sha }}-${{ github.run_number }}
      
      - name: Build
        run: npm run build --if-present

  merge:
    runs-on: ubuntu-latest
    needs: build

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1
      with:
        persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
        fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.

    - name: Configure user
      run: |
        git remote set-url origin "https://${{ secrets.PAT_TOKEN }}@github.com/funas-org/cv-tests.git"

    - name: Get and Update staging branch
      run: |
        git fetch origin staging
        git checkout staging
        git pull origin staging
        git checkout main

    - name: Merge to Main and Push
      run: |
        git merge --ff-only staging
        git push origin main
  
  check-fail:
    runs-on: ubuntu-latest
    needs: [install, lint, build, merge]
    if: failure()
    steps:
    - uses: actions/checkout@v4.1.1

    - name: Check Workflow Status
      run: gh issue create --title "Falha no Workflow" --body "O workflow falhou. Por favor, verifique os logs para mais informações."
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

