name: Using external

on:
  workflow_dispatch:
    inputs:
      run_job:
        description: 'Excecute manually'
        required: true
        default: 'yes'

permissions: write-all

jobs:
  send-api-request:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4.1.1

    - name: Get and Update staging branch
      run: |
        git fetch origin staging
        git checkout staging
        git pull origin staging
        git checkout main
        git merge --ff-only staging

    - name: Push changes
      uses: ad-m/github-push-action@v0.8.0
      with:
        github_token: ${{ secrets.PAT_TOKEN }}
        branch: main